### ISSUE TITLE
Widget not showing switchpositions and switchfunctions

### ISSUE THREAD

**Issue by 40-3-s** [druckgott/getswitchesWdgets#7]

**Comment by druckgott** [comment]
? Did you fix it?

**Comment by 40-3-s** [comment]
> ? Did you fix it?

I missed the special functions and sound part of the description, so it's obviously my fault. Trying to figure that out now.

**Comment by 40-3-s** [comment]
Got it working perfectly. Thanks a lot. Very nice widget!
